name = "MyPrivateRegistry"
uuid = "11353c6a-3072-4f39-979b-4cd4a004ce60"
repo = "https://github.com/ngiann/MyRegistry"
description = "My private registry"

[packages]
9d3c0a80-2a07-4549-acfe-7a6c9ee150ac = { name = "DeterministicESN", path = "D/DeterministicESN" }
