name = "MyPrivateRegistry"
uuid = "11353c6a-3072-4f39-979b-4cd4a004ce60"
repo = "https://github.com/ngiann/MyRegistry"
description = "My private registry"

[packages]
2a76aaee-6cc6-4ca2-80f5-934569e3e54d = { name = "SphericalVI", path = "S/SphericalVI" }
41bbd1a4-0eca-4bcd-b6b1-8656d032eaeb = { name = "ForwardNeuralNetworks", path = "F/ForwardNeuralNetworks" }
9d3c0a80-2a07-4549-acfe-7a6c9ee150ac = { name = "DeterministicESN", path = "D/DeterministicESN" }
b1f9d165-0aea-4f74-aae5-734db6245639 = { name = "ApproximateVIUtilities", path = "A/ApproximateVIUtilities" }
cb277d27-4572-457a-a8ee-2696a40688ee = { name = "ESNAutoencoder", path = "E/ESNAutoencoder" }
