name = "MyPrivateRegistry"
uuid = "11353c6a-3072-4f39-979b-4cd4a004ce60"
repo = "https://github.com/ngiann/MyRegistry"
description = "My private registry"

[packages]
00b2a2d8-fd43-489c-8ddf-9d61fc746162 = { name = "SparseBlackBox", path = "S/SparseBlackBox" }
01547f14-8228-49c5-853c-d3c46473787c = { name = "SimpleMLP", path = "S/SimpleMLP" }
020d689a-7d53-432e-9216-4f61b8e9d61d = { name = "RBFnetwork", path = "R/RBFnetwork" }
0e2f0d3a-ed58-4e79-b814-416dbf662698 = { name = "DiscretisedConvolution", path = "D/DiscretisedConvolution" }
166650a0-0fc3-4b1f-af1e-de1563cd4596 = { name = "Azzalini2DDensity", path = "A/Azzalini2DDensity" }
169c5df3-7e5a-4090-a9f6-c2764bef9338 = { name = "BasisForSpectra", path = "B/BasisForSpectra" }
21605d96-f59a-48f1-9b8f-10329cb5ba4e = { name = "ELBOfyUtilities", path = "E/ELBOfyUtilities" }
29452966-554d-45f8-8f51-f16ef1f654f2 = { name = "GPLVMplus_experiments", path = "G/GPLVMplus_experiments" }
2a76aaee-6cc6-4ca2-80f5-934569e3e54d = { name = "SphericalVI", path = "S/SphericalVI" }
32a276b1-fdac-4448-a3ee-c7eb514ec0f9 = { name = "NormalisedNets", path = "N/NormalisedNets" }
41bbd1a4-0eca-4bcd-b6b1-8656d032eaeb = { name = "ForwardNeuralNetworks", path = "F/ForwardNeuralNetworks" }
4bc70558-c007-47c0-a71b-57423cb29c3c = { name = "PPCASpectra", path = "P/PPCASpectra" }
514699ec-cad0-4573-b799-e90939df45ca = { name = "ExponentialExpectations", path = "E/ExponentialExpectations" }
640a3bb9-347f-47c9-97d8-5dcc1a651101 = { name = "ConvolvedGaussianProcesses", path = "C/ConvolvedGaussianProcesses" }
6700a686-f114-44c7-a16d-e7e2a378161c = { name = "ADPhysicalTransferFunction", path = "A/ADPhysicalTransferFunction" }
6b89a223-e31d-4a8a-8cfc-426c8f4cf287 = { name = "RBFLVM", path = "R/RBFLVM" }
6fc07f5b-fa7b-4f51-aead-263239aaf445 = { name = "ELBOfy", path = "E/ELBOfy" }
99dd9245-5fd5-4439-81a6-2183e70e1908 = { name = "ConvolvedKernel", path = "C/ConvolvedKernel" }
9ca1ba71-c229-46e3-8ae9-21d24b118006 = { name = "SloanUGRIZFilters", path = "S/SloanUGRIZFilters" }
9d3c0a80-2a07-4549-acfe-7a6c9ee150ac = { name = "DeterministicESN", path = "D/DeterministicESN" }
9fd33059-656d-4867-a56b-947448e04143 = { name = "GPLVM_plus_dataset", path = "G/GPLVM_plus_dataset" }
afcdd506-c292-4d2d-8178-f26d054b8ebe = { name = "BasicAugmentedLangrange", path = "B/BasicAugmentedLangrange" }
b1f9d165-0aea-4f74-aae5-734db6245639 = { name = "ApproximateVIUtilities", path = "A/ApproximateVIUtilities" }
bc18901c-f663-4665-a286-cf64e7af24b0 = { name = "SimpleRegressionGP", path = "S/SimpleRegressionGP" }
becc0e91-8ea2-4677-b9da-e014576d6688 = { name = "VISmoothNoise", path = "V/VISmoothNoise" }
c315eb13-d14d-45c6-a93f-2ca8f34325ea = { name = "CDFIntegrals", path = "C/CDFIntegrals" }
c977da63-dc55-4e90-9e9d-5cb77bb2d17a = { name = "LinearRegressionInputUncetainty", path = "L/LinearRegressionInputUncetainty" }
cb277d27-4572-457a-a8ee-2696a40688ee = { name = "ESNAutoencoder", path = "E/ESNAutoencoder" }
d42837a9-6870-44f6-82a5-99dcce1f8faa = { name = "GPLVM", path = "G/GPLVM" }
e6e86137-ec06-4dea-a34b-17dcf4ebba02 = { name = "DirichletMixtures", path = "D/DirichletMixtures" }
ea5a6cf0-6c34-4305-a4f4-b4303448266d = { name = "FFTConvolution", path = "F/FFTConvolution" }
