name = "MyPrivateRegistry"
uuid = "11353c6a-3072-4f39-979b-4cd4a004ce60"
repo = "https://github.com/ngiann/MyRegistry"
description = "My private registry"

[packages]
01547f14-8228-49c5-853c-d3c46473787c = { name = "SimpleMLP", path = "S/SimpleMLP" }
2a76aaee-6cc6-4ca2-80f5-934569e3e54d = { name = "SphericalVI", path = "S/SphericalVI" }
41bbd1a4-0eca-4bcd-b6b1-8656d032eaeb = { name = "ForwardNeuralNetworks", path = "F/ForwardNeuralNetworks" }
6b89a223-e31d-4a8a-8cfc-426c8f4cf287 = { name = "RBFLVM", path = "R/RBFLVM" }
9d3c0a80-2a07-4549-acfe-7a6c9ee150ac = { name = "DeterministicESN", path = "D/DeterministicESN" }
b1f9d165-0aea-4f74-aae5-734db6245639 = { name = "ApproximateVIUtilities", path = "A/ApproximateVIUtilities" }
bc18901c-f663-4665-a286-cf64e7af24b0 = { name = "SimpleRegressionGP", path = "S/SimpleRegressionGP" }
cb277d27-4572-457a-a8ee-2696a40688ee = { name = "ESNAutoencoder", path = "E/ESNAutoencoder" }
ea5a6cf0-6c34-4305-a4f4-b4303448266d = { name = "FFTConvolution", path = "F/FFTConvolution" }
